[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

## Package Configuration

[tool.poetry]
name = "playground"
version = "0.0.0"
description = ""
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
modal = "^0.62.175"
requests = "^2.31.0"
